sudo: required
dist: trusty

language: "node_js"

node_js:
    - "7"

cache: "yarn"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli@1.3.1
  - npm install -g karma

script:
  - "ng test --no-watch --cc"

after_success:
  - npm run coveralls
